### ISSUE TITLE
 invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by kbroughton** [praetorian-inc/snowcat#30]
Deploying following the readme as a kubernetes job the following error occurred

time="2021-10-27T17:48:18Z" level=debug msg="connecting to xds" addr="10.x.y.z:15010"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1417e72]

goroutine 1 [running]:
github.com/praetorian-inc/snowcat/pkg/xds.(*Client).Version(0xc0005df2d8, {0x19806f0, 0xc00013c020})
	github.com/praetorian-inc/snowcat/pkg/xds/client.go:169 +0xd2
github.com/praetorian-inc/snowcat/pkg/xds.NewClient({0xc0005df2d8, 0x12})
	github.com/praetorian-inc/snowcat/pkg/xds/client.go:64 +0x173
github.com/praetorian-inc/snowcat/pkg/runner/istiod.hasDiscoveryService({0xc000bdc4d0, 0xc00004ab80})
	github.com/praetorian-inc/snowcat/pkg/runner/istiod/istiod.go:77 +0x37
github.com/praetorian-inc/snowcat/pkg/runner/istiod.isDebugIstiod({0xc000bdc4d0, 0x19806f0})
	github.com/praetorian-inc/snowcat/pkg/runner/istiod/istiod.go:94 +0x2d
github.com/praetorian-inc/snowcat/pkg/runner/istiod.(*kubeletStrategy).Run(0xc0001de540, 0xc000382660)
	github.com/praetorian-inc/snowcat/pkg/runner/istiod/istiod.go:138 +0xd65
github.com/praetorian-inc/snowcat/pkg/runner.(*Runner).Run(0xc000bee2d0, 0x0)
	github.com/praetorian-inc/snowcat/pkg/runner/runner.go:74 +0x287
github.com/praetorian-inc/snowcat/pkg/runner.Runners.Run({0xc000bef450, 0x3, 0xc0006bf3f8}, 0xc000382660, 0x0)
	github.com/praetorian-inc/snowcat/pkg/runner/runner.go:94 +0x12e7
github.com/praetorian-inc/snowcat/pkg/cli.RunSnowcat({0xc00054c0f0, 0x0, 0x0})
	github.com/praetorian-inc/snowcat/pkg/cli/root.go:232 +0x2ab
github.com/praetorian-inc/snowcat/pkg/cli.glob..func2(0x264bde0, {0xc00054c0f0, 0x5, 0x5})
	github.com/praetorian-inc/snowcat/pkg/cli/root.go:95 +0x27
github.com/spf13/cobra.(*Command).execute(0x264bde0, {0xc000138130, 0x5, 0x5})
	github.com/spf13/cobra@v1.2.1/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x264bde0)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
github.com/praetorian-inc/snowcat/pkg/cli.Execute()
	github.com/praetorian-inc/snowcat/pkg/cli/root.go:187 +0x35
main.main()
	github.com/praetorian-inc/snowcat/cmd/snowcat/main.go:24 +0x17

**Comment by dkaman** [comment]
Hey Kesten, do you mind giving us some more info on the cluster? Is it managed?

**Comment by kbroughton** [comment]
yes, managed GKE. 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.14-gke.1900", GitCommit:"abc4e63ae76afef74b341d2dba1892471781604f", GitTreeState:"clean", BuildDate:"2021-09-07T09:21:04Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1

**Comment by sfunkernw** [comment]
Same or similar issue in a Gardener cluster with [Kyma](https://kyma-project.io) runtime:

```
kubectl -n default apply -f https://raw.githubusercontent.com/praetorian-inc/snowcat/main/deploy/job.yaml
job.batch/snowcat created
...
kubectl -n default logs jobs/snowcat
time="2025-10-31T21:11:05Z" level=warning msg="configuration file not found"
time="2025-10-31T21:11:05Z" level=info msg="successfully loaded config file" configFile=snowcat.yml
time="2025-10-31T21:11:05Z" level=info msg="running discovery strategy" runner=Kubelet strategy=default-gateway
time="2025-10-31T21:11:05Z" level=info msg="attempting to locate default gateway"
time="2025-10-31T21:11:05Z" level=info msg="discovered default gateway" gateway=169.254.1.1
time="2025-10-31T21:11:05Z" level=info msg="scanning for additional potential gateways using HTTP scanner"
time="2025-10-31T21:11:05Z" level=debug msg="resulting kubelet apis" kubeletAddresses="[]"
time="2025-10-31T21:11:05Z" level=info msg="running discovery strategy" runner=Namespace strategy=envoy
time="2025-10-31T21:11:05Z" level=debug msg="sending HTTP request to envoy" method=GET url="http://localhost:15000/config_dump"
time="2025-10-31T21:11:05Z" level=info msg="running discovery strategy" runner="Istio Control Plane" strategy=kubelet
time="2025-10-31T21:11:05Z" level=info msg="running discovery strategy" runner="Istio Control Plane" strategy=istiod
time="2025-10-31T21:11:05Z" level=debug msg="connecting to xds" addr="istiod.istio-system.svc.cluster.local:15010"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1417e72]

goroutine 1 [running]:
github.com/praetorian-inc/snowcat/pkg/xds.(*Client).Version(0xc001d32810, {0x19806f0, 0xc000148020})
        github.com/praetorian-inc/snowcat/pkg/xds/client.go:169 +0xd2
github.com/praetorian-inc/snowcat/pkg/xds.NewClient({0xc001d32810, 0x2b})
        github.com/praetorian-inc/snowcat/pkg/xds/client.go:64 +0x173
github.com/praetorian-inc/snowcat/pkg/runner/istiod.hasDiscoveryService({0xc001d327e0, 0x1b})
        github.com/praetorian-inc/snowcat/pkg/runner/istiod/istiod.go:77 +0x37
github.com/praetorian-inc/snowcat/pkg/runner/istiod.(*istiodStrategy).Run(0xc00238d180, 0xc0001449c0)
        github.com/praetorian-inc/snowcat/pkg/runner/istiod/istiod.go:179 +0x85
github.com/praetorian-inc/snowcat/pkg/runner.(*Runner).Run(0xc000e9a2d0, 0x1)
        github.com/praetorian-inc/snowcat/pkg/runner/runner.go:74 +0x287
github.com/praetorian-inc/snowcat/pkg/runner.Runners.Run({0xc000e9b450, 0x3, 0x0}, 0xc0001449c0, 0x0)
        github.com/praetorian-inc/snowcat/pkg/runner/runner.go:94 +0x12e7
github.com/praetorian-inc/snowcat/pkg/cli.RunSnowcat({0xc0000bc410, 0x0, 0x0})
        github.com/praetorian-inc/snowcat/pkg/cli/root.go:232 +0x2ab
github.com/praetorian-inc/snowcat/pkg/cli.glob..func2(0x264bde0, {0xc0000bc410, 0x5, 0x5})
        github.com/praetorian-inc/snowcat/pkg/cli/root.go:95 +0x27
github.com/spf13/cobra.(*Command).execute(0x264bde0, {0xc000144130, 0x5, 0x5})
        github.com/spf13/cobra@v1.2.1/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x264bde0)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.2.1/command.go:902
github.com/praetorian-inc/snowcat/pkg/cli.Execute()
        github.com/praetorian-inc/snowcat/pkg/cli/root.go:187 +0x35
main.main()
        github.com/praetorian-inc/snowcat/cmd/snowcat/main.go:24 +0x17
```
